### PR TITLE
refactor: esm first

### LINKED ISSUE #371: Cannot use with Typescript
```sh
mkdir -p /tmp/hc
cd /tmp/hc
npm init -y
npm i typescript @hebcal/core @hebcal/noaa tslib
echo "export * from '@hebcal/core'" > index.ts
cat >tsconfig.json <<EOL
{
  "include": ["index.ts"],
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "declaration": true,
    "moduleResolution": "NodeNext",
    "importHelpers": true,
    "sourceMap": true,
    "inlineSources": true
  }
}
EOL
npx tsc
```

> node_modules/@hebcal/core/hebcal.d.ts:1:29 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@hebcal/noaa")' call instead.
> 
> 1 import { GeoLocation } from '@hebcal/noaa';
>                              ~~~~~~~~~~~~~~
> 
> 
> Found 1 error in node_modules/@hebcal/core/hebcal.d.ts:1

See #365

### PR DESCRIPTION
**Pull request by bennypowers**
makes legacy cjs the special case
add package exports
fix some .d.ts tsc errors
closes #371

### CODE REVIEW

**Comment by bennypowers** [comment]
Sweet, I got PR number 365 :smile:

**Review by mjradwin — APPROVED** [review]

**Comment by bennypowers** [comment]
:/ classic react: "we won't let you do the standard thing because we're cleverer than tc39 and whatwg"

**Comment by bennypowers** [comment]
fwiw, i've dug plenty of teams out from under their mess of react nonsense, and it's *possible* to get a react app running with javascript written to standards shipped >2 years ago (export maps), it's just not as straightforward and pleasant as never having fallen for the react malarkey in the first place

**Comment by bennypowers** [comment]
i'd like to suggest that if users can't use the thing which was ubiquitously shipped over two years ago because their framework is too crufty, that they should just use the old thing

**Comment by mjradwin** [comment]
I'm trying to get this PR merged but it's failing on the test phase.

Possibly related to adding `"type": "module"` to the `package.json` file?

```
  Uncaught exception in src/sedra.spec.js

  Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/runner/work/hebcal-es6/hebcal-es6/src/hdate' imported from /home/runner/work/hebcal-es6/hebcal-es6/src/sedra.spec.js
```

Do you know how to fix this?

**Comment by bennypowers** [comment]
Thanks for the ping. I ported all the import specs over and added import attributes, the tests now run in node 20. it may be possible to allow earlier node versions by building with rollup plugins.

several tests appear to fail with off-by-one errors

**Comment by mjradwin** [comment]
Thanks for taking a look! It looks like Node 16 is no longer in LTS, but we're committed to supporting Node 18 through its LTS maintenance phase through April 2025. We'll work in as many of these patches as we can without breaking Node 18 and see if we can get to the finish line!

**Comment by bennypowers** [comment]
Sounds good. In that case I suggest that we add a build step which converts the JSON output from the .po files into JavaScript modules. This can be as simple as pretending `expprt default ` to the first line and changing the file extension to .js

**Comment by mjradwin** [comment]
All changes should now be in v5.0.3. Can you confirm that it's working for you and we can close this pull request?

**Pull request closed without merging**
