### PR TITLE
Attempt to port tachanun from JS to TS

### PR DESCRIPTION
**Pull request by mjradwin**
Hi @YizYah, I'm trying a small experiment to mix TypeScript in with this repo and I'm having trouble getting the unit tests to work correctly. Do you have time to take a look?

### CODE REVIEW

**Comment by YizYah** [comment]
@mjradwin about to head out... let me have a look tomorrow, bli neder.

**Comment by mjradwin** [comment]
Thanks! Obviously no urgency here - this is the smallest experiment that I could think of so we can begin to do the JS => TS rewrite.

**Comment by mjradwin** [comment]
One idea is to explore rewriting all of the tests from Ava to Jest. This would be a bit tedious, but Jest seems to be more widely used than Ava, and therefore may have better support for projects mixing typescript and JS.

**Comment by mjradwin** [comment]
Scratch this. I've figured out how to make this work by rewriting unit tests from Ava to Jest. Closing this PR.

**Comment by YizYah** [comment]
For the record, I think it's the right choice. I was a real Ava enthusiast a few years ago, but everyone uses Jest today. That makes it smoother to work with AI or find answers to questions, and relevant code is better maintained (such as VS code plugins). We live in a winner-takes-all world LOL.

**Pull request closed without merging**
